apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ke4gxlsdq-nodejs 
  janus-idp.io/tekton: ke4gxlsdq-nodejs
  backstage.io/kubernetes-id: ke4gxlsdq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ke4gxlsdq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml